project_id = "mnijromffaalvpadojbj"

[functions.rome-auth]
verify_jwt = false

[functions.auth-security]
verify_jwt = false

[functions.crypto-utils]
verify_jwt = true

[functions.notify]
verify_jwt = true

[functions.nomad-chat]
verify_jwt = true

[functions.admin-operations]
verify_jwt = true

[functions.grant-admin]
verify_jwt = true

[functions.approve-team]
verify_jwt = false
